config/routes.rb
Gearstantial::Application.routes.draw do

  resources :items 
  resources :employees

  root 'items#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :items

  validates :name, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :employee

  validates_uniqueness_of :serial
  validates :name, presence: true #requires a name so that user gets a link to it when done
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :find_employee, :only => [:show, :edit, :update, :destroy]
  def new
    @employee = Employee.new
    @locations = ["Seattle HQ", "Seattle South", "San Francisco"]
  end

  def create
    # puts "hello #{params}" 
    # name = params[:employee][:name]
    # location = params[:employee][:location]
    # status = params[:employee][:status]

    @employee = Employee.new(permitted_params)
    @employee.save

    #redirect_to items_path
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def edit
  end

  def update
    @employee.update_attributes(permitted_params)
    @employee.save

    #redirect_to employees_path, flash: flash
  end

  def index
    #redirect_to items_path, flash: flash
    @employee = Employee.all
  end

  def destroy
    employee = Employee.find(params[:id])
    employee.destroy
    flash[:notice] = "Name: #{@employee.name} was deleted"

    redirect_to items_path, flash: flash
  end

  def permitted_params
    params.require(:employee).permit(:name, :location, :status)
  end

def find_employee
    #binding.pry
    @employee = Employee.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :find_item, :only => [:show, :edit, :update, :destroy]
  
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(permitted_params)

    if @item.save
      redirect_to items_path, notice: "Item was created with id # #{@item.id}"
    else
      render :new 
    end
  end

  def show
  end

  def edit
  end

  def update
    @item.update_attributes(permitted_params)

    flash[:notice] = "Item was updated with id # #{@item.id}"
    redirect_to items_path, flash: flash
  end

  def index
    @items = Item.all
    @employees = Employee.all
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    flash[:notice] = "Item name #{@item.name} was deleted"
    redirect_to items_path, flash: flash
  end

  private

  def permitted_params
    params.require(:item).permit(:name, :serial, :year, :location, :purchase_date, :purchase_price, :notes, :employee_id)
  end

  def find_item
    #binding.pry
    @item = Item.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/edit.html.erb
<h2>Edit Employee</h2>
<% flash.each do |name, msg| %>
  <p><%= "#{name} - #{msg}" %>To Edit, modify the form inputs</p>
<% end %>

<%= simple_form_for @employee do |f| %>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :status, collection: ["Active", "Off-Site", "Contractor", "Need requested"], prompt: "Select status" %>
  <%= f.button :submit %>
<% end %>

<br />
<%= link_to  "Home", "/items" %>

app/views/employees/index.html.erb
Hello there!

app/views/employees/new.html.erb
<h1>Enter Employee!</h1>
<p>Return <%= link_to  "Home", root_path %></p>
<h3>Please Fill Out Form</h3>

<%= simple_form_for @employee, html_options: { class: "form-horizontal" } do |f| %>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :status, collection: ["Active", "Off-Site", "Contractor", "Need requested"], prompt: "Select status" %>
  <%= f.button :submit %>
<% end %>

app/views/employees/show.html.erb
<h2>Employee Details</h2>
<p><%= link_to  "Back", root_path %>  
  <%= link_to  "Edit Employee", "/employees/#{@employee.id}/edit" %>   
  <%= link_to  "Add Employee", new_employee_path %>
  <%= button_to "Remove Employee", employee_path(@employee), method: :delete, data: { confirm: "Are you sure?" } %>
</p>
 <ul>
   <li>Name: <%= @employee.name %></li>
   <li>Location: <%= @employee.location %> </li>
   <li>Status: <%= @employee.status %></li>
</ul>

app/views/items/_form.html.erb
<%= simple_form_for @item, html_options: { class: "form-horizontal" } do |f| %>
  <%= f.input :name %>
  <%= f.input :serial %>
  <%= f.input :year, collection: 2008..2014, prompt: "Production Year" %>
  <%= f.input :purchase_date, as: :date %>
  <%= f.input :purchase_price, as: :float %>
  <%= f.input :notes, as: :text %>
  <%= f.input :location, collection: ["Seattle HQ", "Seattle South", "San Francisco"], prompt: "Select Location" %>
  <%= f.association :employee %>
  <%= f.button :submit %>
<% end %>

app/views/items/edit.html.erb
<h2>Edit Item</h2>
<% flash.each do |name, msg| %>
  <p><%= "#{name} - #{msg}" %>To Edit, modify the form inputs</p>
<% end %>

<%= render "form" %>

<br />
<%= link_to  "Home", "/items" %>

app/views/items/index.html.erb
<% flash.each do |name, msg| %>
  <p><%= "#{name} - #{msg}" %></p>
<% end %>

<h2> Substantial Inventory!</h2>

<h4>Your Items</h4>
<%= link_to  "Add Item", new_item_path %> 
<pre>Inventory statistics will go here</pre>
<table class="table">
  <tr>
    <th>Item Name</th>
    <th>Serial</th>
    <th>Year Made</th>
    <th>Location</th>
    <th>Date Purchased</th>
    <th>Purchase Price</th>
    <th>Additional Notes</th>
    <th>Assigned To:</th>
  </tr>
  <% @items.each do |item| %>
    <tr>
      <td><%= link_to item.name, "items/#{item.id}" %> </td>
      <td><%= item.serial %> </td>
      <td><%= item.year %> </td>
      <td><%= item.location %></td>
      <td><%= item.purchase_date.strftime("%D") %> </td>
      <td><%= number_to_currency(item.purchase_price, precision:2) %></td>
      <td><%= item.notes %></td>
      <td><%= item.employee.name if item.employee %></td>
    </tr>
  <% end %>
</table>

<h4>Employees</h4>
<%= link_to  "Add Employee", new_employee_path %>
<table class="table">
  <tr>
    <th>Employee Name</th>
    <th>Location</th>
    <th>Status</th>
    <th>Created On</th>
    <th>Updated On</th>
  </tr>
  <% @employees.each do |employee| %>
    <tr>
      <td><%= link_to employee.name, "employees/#{employee.id}" %> </td>
      <td><%= employee.location %></td>
      <td><%= employee.status %></td>
      <td><%= employee.created_at %></td>
      <td><%= employee.updated_at %></td>
    </tr>
  <% end %>
</table>

app/views/items/new.html.erb
<h2>Enter Item!</h2>
<p>Return <%= link_to  "Home", root_path %></p>
<h3>Please Fill Out Form</h3>

<%= render "form" %>

app/views/items/show.html.erb
<h2>Item Details</h2>
<p><%= link_to  "Back", root_path %>  
  <%= link_to  "Edit Item", "/items/#{@item.id}/edit" %>   
  <%= button_to "Remove Item", item_path(@item), method: :delete, data: { confirm: "Are you sure?" } %>
</p>
 <ul>
   <li>Item Name: <%= @item.name %></li>
   <li>Serial:  <%= @item.serial %> </li>
   <li>Production Year: <%= @item.year %></li>
   <li>Purchase Date: <%= @item.purchase_date %></li>
   <li>Location: <%= @item.location %></li>
   <li>Purchase Price: $<%= @item.purchase_price %></li>
   <li>Created On: <%= @item.created_at %></li>
   <li>Updated On: <%= @item.updated_at %></li>
   <li>Notes: <%= @item.notes %> </li>
   <li>Assigned To: <%= @item.employee.name if @item.employee %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <div class="container">
    <title>Gearstantial - Vy's Rails App</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </div>
</head>
<body>

<%= yield %>

</body>
</html>